spring.application.name=cloudfare-r2-test
spring.config.import=optional:file:.env[.properties]
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
springdoc.swagger-ui.path=/swagger.html
storage.access-key=${STORAGE_ACCESS_KEY_ID}
storage.secret-key=${STORAGE_SECRET_KEY}
storage.endpoint=${STORAGE_ENDPOINT}
storage.bucket-name=${STORAGE_BUCKET_NAME}
storage.region=${STORAGE_REGION}


