spring.application.name=cloudfare-r2-test
spring.config.import=optional:file:.env[.properties]
springdoc.swagger-ui.path=/swagger.html
r2.access-key=${R2_ACCESS_KEY_ID}
r2.secret-key=${R2_SECRET_KEY}
r2.endpoint=${R2_ENDPOINT}
r2.bucket-name=${R2_BUCKET_NAME}


